ProxyUrl: "http://bapi.51daili.com/getapi2?linePoolIndex=1&packid=4&unkey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ImEyMjE3ODA0MDM4fDF8MjAwfFd1WWlEYWlMaSI.7kr6DOl6diKZVmhvSfxRl1_wbUuPytg76lrJigxnXDI&tid=&qty=200&time=1&port=1&format=txt&ss=1&css=&pro=&city=&dt=0&ct=0&service=1&usertype=17&accessName=a2217804038"
ExpTime: 25
IntervalTime: 3
Auth:
  UserName: ""
  Password: ""
DetailLog: false
