name: GoRelease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "amd64"
            goos: darwin
          - goarch: "arm64"
            goos: darwin
          - goarch: arm64
            goos: windows
  
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          executable_compression: upx
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21.4 
          binary_name: "ProxyPool"
          extra_files: config.yml
