name: GoRelease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
            
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
          binary_name: "ProxyPool"
          extra_files: config.yml
